# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
sudo: required

r_packages:
  - devtools

bioc_required: true

bioc_packages:
  - seqLogo
  - Biostrings
  - msa

env:
  - WARNINGS_ARE_ERRORS=false
  - NOT_CRAN=true

before_script:
  - sudo apt install seq-gen