# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

sudo: required

bioc_required: true

r_github_packages:
  - jimhester/covr

bioc_packages:
  - seqLogo
  - Biostrings

env:
  - WARNINGS_ARE_ERRORS=false
  - NOT_CRAN=true

after_success:
  - Rscript -e 'library(covr);codecov()'